import { Activity, AlertTriangle, BarChart2, Shield } from "lucide-react";
import type { PredictResponse } from "../api";
import { ConfBar, EmptyState, InputChip, MODULE_META, RiskGauge, VerdictBadge } from "./shared";
import { toScore, toVerdict } from "../api";

export default function Dashboard({ result, caseId, onCaseClick }: { result: PredictResponse | null; caseId: string; onCaseClick: () => void }) {
  const score = result ? toScore(result.combined_risk_probability) : null;
  const modules = result?.contributing_modules ?? [];
  const verdict = result ? toVerdict(result.verdict) : null;
  const cards = [
    { label: "Latest Risk Score", value: score === null ? "—" : score, unit: score === null ? undefined : "/ 100", icon: Shield, color: "#3B82F6" },
    { label: "Latest Verdict", value: verdict ?? "—", icon: AlertTriangle, color: "#B24A2F" },
    { label: "Modules Analyzed", value: result ? modules.length : "—", icon: BarChart2, color: "#1F8955" },
    { label: "Fusion Method", value: result?.fusion_method ?? "—", icon: Activity, color: "#2DBF7C" },
  ];
  return <div className="flex flex-col gap-6 p-6">
    <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{cards.map(({ label, value, unit, icon: Icon, color }) => <div key={label} className="rounded-xl p-4 flex flex-col gap-3" style={{ background: "var(--card)", border: "1px solid var(--border)" }}><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-medium uppercase tracking-widest" style={{ color: "var(--muted-foreground)" }}>{label}</p><div className="flex items-baseline gap-1 mt-1"><span className="text-xl font-bold font-mono truncate" style={{ color: "var(--foreground)" }}>{value}</span>{unit && <span className="text-sm" style={{ color: "var(--muted-foreground)" }}>{unit}</span>}</div></div><div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: `${color}22` }}><Icon size={16} style={{ color }} /></div></div><span className="text-xs" style={{ color: "var(--muted-foreground)" }}>{result ? "From latest backend response" : "No live data yet"}</span></div>)}</div>
    <div className="grid grid-cols-1 xl:grid-cols-5 gap-4"><div className="xl:col-span-2 flex flex-col gap-4"><div className="rounded-xl p-6 flex flex-col items-center gap-2" style={{ background: "var(--card)", border: "1px solid var(--border)" }}><div className="flex items-center justify-between w-full mb-2"><h3 className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>Fused Risk Score</h3><span className="text-xs font-mono px-2 py-0.5 rounded" style={{ background: "var(--secondary)", color: "var(--muted-foreground)" }}>{result ? caseId : "No case yet"}</span></div>{result ? <RiskGauge score={score!} /> : <p className="text-sm py-16" style={{ color: "var(--muted-foreground)" }}>Submit an analysis to see the fused risk score.</p>}{result && <p className="text-xs text-center max-w-48 mt-1" style={{ color: "var(--muted-foreground)" }}>{result.explanation}</p>}</div><div className="rounded-xl p-4 flex flex-col gap-3" style={{ background: "var(--card)", border: "1px solid var(--border)" }}><h3 className="text-sm font-semibold mb-1" style={{ color: "var(--foreground)" }}>Module Risk Breakdown</h3>{result ? modules.map(module => { const meta = MODULE_META[module.module]; const risk = toScore(module.risk_probability); return <div key={module.module} className="flex items-center gap-3"><div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${meta.color}20`, color: meta.color }}><meta.icon size={14} /></div><div className="flex-1 min-w-0"><span className="text-xs font-medium truncate" style={{ color: "var(--foreground)" }}>{meta.label}</span><ConfBar value={risk} color={meta.color} /></div><span className="font-mono text-xs font-semibold w-8 text-right" style={{ color: risk > 65 ? "var(--risk-high)" : risk > 35 ? "var(--risk-suspicious)" : "var(--risk-safe)" }}>{risk}%</span></div>; }) : <p className="text-sm py-4" style={{ color: "var(--muted-foreground)" }}>No module results yet.</p>}</div></div>
      <div className="xl:col-span-3 rounded-xl flex flex-col" style={{ background: "var(--card)", border: "1px solid var(--border)" }}><div className="flex items-center justify-between px-4 py-3 border-b" style={{ borderColor: "var(--border)" }}><h3 className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>Latest Case</h3><span className="text-xs" style={{ color: "var(--muted-foreground)" }}>{result ? "Backend response" : "No live cases"}</span></div><div className="overflow-auto scrollbar-hide flex-1"><table className="w-full text-sm"><thead><tr style={{ borderBottom: "1px solid var(--border)" }}>{["Time", "Case ID", "Inputs", "Score", "Verdict", "Source"].map(header => <th key={header} className="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--muted-foreground)" }}>{header}</th>)}</tr></thead><tbody>{result ? <tr className="cursor-pointer" style={{ borderBottom: "1px solid var(--border)" }} onClick={onCaseClick}><td className="px-4 py-3 font-mono text-xs" style={{ color: "var(--muted-foreground)" }}>{new Date().toLocaleTimeString()}</td><td className="px-4 py-3 font-mono text-xs font-semibold" style={{ color: "var(--accent)" }}>{caseId}</td><td className="px-4 py-3"><div className="flex gap-1">{modules.map(module => <InputChip key={module.module} type={module.module} />)}</div></td><td className="px-4 py-3 font-mono text-sm font-bold" style={{ color: score! > 65 ? "var(--risk-high)" : score! > 35 ? "var(--risk-suspicious)" : "var(--risk-safe)" }}>{score}</td><td className="px-4 py-3"><VerdictBadge verdict={verdict!} /></td><td className="px-4 py-3 text-xs" style={{ color: "var(--muted-foreground)" }}>Backend</td></tr> : <tr><td colSpan={6}><EmptyState>Submit an analysis to populate this view.</EmptyState></td></tr>}</tbody></table></div></div></div>
  </div>;
}
